kind: Service
apiVersion: v1
metadata:
  name: restserver
spec:
  selector:
    name: restserver
  ports:
    - port: 8000
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: restserver
  name: restserver
spec:
  replicas: 6
  template:
    metadata:
      labels:
        name: restserver
    spec:
      containers:
        - image: quay.io/ywarezk/rest
          name: restserver
          ports:
            - containerPort: 8000
