# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 08:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2016, 1, 15, 8, 59, 36, 919719))),
                ('modified_data', models.DateTimeField(auto_now=True)),
                ('severity', models.PositiveIntegerField(choices=[(0, b'None'), (1, b'Minor'), (2, b'Medium'), (3, b'Important'), (4, b'Critical')], default=0)),
                ('assigned_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2016, 1, 15, 8, 59, 36, 919719))),
                ('modified_data', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='tags',
            field=models.ManyToManyField(to='rest_server.Tag'),
        ),
        migrations.AddField(
            model_name='bug',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to=settings.AUTH_USER_MODEL),
        ),
    ]
